# Docker Compose for local development
# BUG #541-545 FIX: Multi-service orchestration

version: '3.8'

services:
  # PostgreSQL Database
  db:
    image: postgres:15-alpine
    container_name: minesweeper-db
    environment:
      POSTGRES_DB: minesweeper
      POSTGRES_USER: minesweeper
      POSTGRES_PASSWORD: ${DB_PASSWORD:-minesweeper_dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./server/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U minesweeper"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: minesweeper-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 5

  # Application Server
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: minesweeper-app
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://minesweeper:${DB_PASSWORD:-minesweeper_dev}@db:5432/minesweeper
      REDIS_URL: redis://redis:6379
      FLASK_ENV: ${FLASK_ENV:-development}
      SECRET_KEY: ${SECRET_KEY:-dev_secret_key_change_in_production}
      JWT_SECRET: ${JWT_SECRET:-dev_jwt_secret_change_in_production}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev_refresh_secret_change_in_production}
      CORS_ORIGINS: ${CORS_ORIGINS:-*}
      MAX_PLAYERS_PER_ROOM: ${MAX_PLAYERS_PER_ROOM:-10}
      MAX_SCORE: ${MAX_SCORE:-100000}
      MAX_TIME: ${MAX_TIME:-172800}
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app/server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 3s
      retries: 3

  # Nginx Reverse Proxy (production)
  nginx:
    image: nginx:alpine
    container_name: minesweeper-nginx
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./server/web:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
    profiles:
      - production

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  default:
    name: minesweeper-network
