[phases.setup]
nixPkgs = ["python311", "pip"]

[phases.install]
cmds = [
  "python3.11 -m venv /opt/venv",
  ". /opt/venv/bin/activate",
  "pip install --upgrade pip",
  "pip install -r server/requirements.txt"
]

[start]
cmd = ". /opt/venv/bin/activate && bash start.sh"
